name: 'Deploy :edge on Schedule'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    name: 'Build Images'
    uses: ironashram/docker-mailserver/.github/workflows/generic_build.yml@master

  run-tests:
    name: 'Test AMD64 Image'
    needs: build-images
    uses: ironashram/docker-mailserver/.github/workflows/generic_test.yml@master
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}

  publish-images:
    name: 'Publish Images'
    needs: [build-images, run-tests]
    uses: ironashram/docker-mailserver/.github/workflows/generic_publish.yml@master
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}
    secrets: inherit
